export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const CUSTOMER_REMOVE_ALL = 'CUSTOMER_REMOVE_ALL';
export const CUSTOMER_REMOVE = 'CUSTOMER_REMOVE';
export const CUSTOMER_GET_ALL = 'CUSTOMER_GET_ALL';
// export const CUSTOMER_GET = 'CUSTOMER_GET';
export const CUSTOMER_UPDATE = 'CUSTOMER_UPDATE';
export const CUSTOMER_ADD = 'CUSTOMER_ADD';
export const CUSTOMER_MULTY_ADD = 'CUSTOMER_MULTY_ADD';
